# -*- coding: utf-8 -*-
"""紐西蘭版 i18n 英文翻譯（新鍵與特化鍵）"""

NZ_EN = {
    # ── 島嶼 ──
    '北島': 'North Island', '南島': 'South Island',
    '島嶼制霸': 'Island domination', '島嶼足跡': 'Island footprints',
    '大區評分': 'Region rating', '該島': 'the island',

    # ── 大區 tagline ──
    '紐西蘭最北端的亞熱帶海岸，九十里海灘與島嶼灣的度假天堂。': "NZ's subtropical northern tip — Ninety Mile Beach and the Bay of Islands.",
    '帆船之都與天空塔，雙港與火山錐交織的南太平洋都會。': 'The City of Sails — Sky Tower, twin harbours and volcanic cones.',
    '哈比屯與螢火蟲洞，中土世界的綠色心臟。': 'Hobbiton and glow-worm caves — the green heart of Middle-earth.',
    '羅托魯瓦的地熱與毛利文化，芒格努伊山的度假海灘。': "Rotorua's geothermal wonders and Māori culture, with Mount Maunganui's beaches.",
    '全球最早迎來日出的城市，衝浪與霞多麗的故鄉。': 'The first city in the world to see the sunrise — surfing and Chardonnay country.',
    '納皮爾的裝飾藝術與紅酒之丘，塘鵝棲息的阿卡蘭吉海岸。': "Napier's Art Deco streets and vineyard hills, with gannets on the Ahuriri coast.",
    '埃格蒙特火山下的完美錐形，衝浪與乳業之鄉。': 'The perfect cone of Mount Taranaki — surf beaches and dairy country.',
    '旺格努伊河與玻璃藝術之城，馬納瓦圖平原的農場風光。': 'The Whanganui River and its glass-art town, set on the Manawatū plains.',
    '風之城與電影首都，蒂帕帕、纜車與咖啡文化。': "Windy capital and film city — Te Papa, the Cable Car and café culture.",
    '亞伯塔斯曼的金色沙灘與陽光，啤酒花與藝術小鎮。': 'Golden beaches of Abel Tasman, hop fields and sunny small towns.',
    '紐西蘭地理中心，陽光、啤酒與穿戴藝術之城。': 'The geographic centre of NZ — sunshine, craft beer and wearable art.',
    '長相思白葡萄酒之都，峽灣千灣與海豚共遊。': 'Sauvignon Blanc capital — sounds, green-lipped mussels and dolphins.',
    '冰河與薄餅岩的狂野海岸，玉石與銀魚的故鄉。': 'Wild coast of glaciers and Pancake Rocks — greenstone and whitebait country.',
    '花園城市與庫克山雪峰，特卡波湖的星空保護區。': "Garden city and Aoraki's peaks, with Lake Tekapo's dark-sky reserve.",
    '皇后鎮的極限運動與瓦納卡湖，但尼丁的蘇格蘭風情。': "Queenstown's adventure hub, Lake Wānaka and Dunedin's Scottish soul.",
    '峽灣國家公園與米爾福德峽灣，世界第八大奇蹟。': 'Fiordland and Milford Sound — the eighth wonder of the world.',

    # ── 美食 ──
    '海鮮拼盤': 'Seafood platter', '奇異果': 'Kiwifruit', '綠殼貽貝': 'Green-lipped mussels',
    '海濱生蠔': 'Harbour oysters', '魚市海鮮': 'Fish Market seafood', '精品咖啡': 'Specialty coffee',
    '農場乳酪': 'Farmhouse cheese', '岩漿窯烤披薩': 'Hangi-fired pizza', '懷卡托牛肉': 'Waikato beef',
    '毛利杭吉料理': 'Hāngī feast', '芒格努伊炸魚': 'Mount Maunganui fish & chips',
    '霞多麗白酒': 'Chardonnay', '吉斯伯恩牛肉': 'Gisborne beef', '現捕海鮮': 'Freshly caught seafood',
    '霍克斯灣紅酒': "Hawke's Bay red wine", '牧場羊排': 'Farm lamb', '新鮮莓果': 'Fresh berries',
    '塔拉納基乳酪': 'Taranaki cheese', '新普利茅斯咖啡': 'New Plymouth coffee', '火山坡乳製品': 'Volcano-side dairy',
    '農場起司': 'Farmhouse cheese', '帕默斯頓北咖啡': 'Palmerston North coffee', '河畔鮮魚': 'River fish',
    '惠靈頓咖啡': 'Wellington coffee', '街頭美食': 'Street food', '精釀啤酒': 'Craft beer',
    '莫圖伊卡啤酒花料理': 'Hop-infused cuisine', '麥普阿生蠔': 'Mapua oysters', '峽灣鮭魚': 'Salmon',
    '尼爾森精釀啤酒': 'Nelson craft beer', '當地莓果': 'Local berries', '海灣海鮮': 'Bay seafood',
    '長相思白葡萄酒': 'Sauvignon Blanc', '帝王鮭魚': 'King salmon',
    '銀魚煎餅': 'Whitebait fritters', '西海岸綠玉牛排': 'Greenstone country beef', '野生漿果': 'Wild berries',
    '坎特伯雷羊排': 'Canterbury lamb', '高山鮭魚': 'Alpine salmon', '基督城咖啡': 'Christchurch coffee',
    '中奧塔哥黑皮諾': 'Central Otago Pinot Noir', '石窯乳酪': 'Stone-fired cheese',
    '布拉夫生蠔': 'Bluff oysters', '南地牛肉': 'Southland beef', '藍鱈魚': 'Blue cod',

    # ── 景點 ──
    '雷因格海角': 'Cape Reinga', '九十里海灘': 'Ninety Mile Beach', '島嶼灣': 'Bay of Islands', '懷唐伊條約屋': 'Waitangi Treaty Grounds',
    '天空塔': 'Sky Tower', '奧克蘭海港大橋': 'Auckland Harbour Bridge', '懷希基島': 'Waiheke Island', '一樹山': 'One Tree Hill',
    '哈比屯': 'Hobbiton Movie Set', '懷托摩螢火蟲洞': 'Waitomo Glowworm Caves', '雷格蘭海灘': 'Raglan Beach', '漢密爾頓花園': 'Hamilton Gardens',
    '羅托魯瓦地熱區': 'Rotorua Geothermal Park', '蒂普亞毛利村': 'Te Puia Māori Village', '芒格努伊山': 'Mount Maunganui', '懷奧塔普地熱仙境': 'Wai-O-Tapu Thermal Wonderland',
    '東角燈塔': 'East Cape Lighthouse', '蒂皮亞': 'Te Pia', '托拉加灣': 'Tolaga Bay', '吉斯伯恩酒莊': 'Gisborne wineries',
    '納皮爾裝飾藝術街區': 'Napier Art Deco Quarter', '蒂瑪塔峰': 'Te Mata Peak', '拐子角塘鵝棲息地': 'Cape Kidnappers Gannet Colony', '霍克斯灣酒莊': "Hawke's Bay wineries",
    '塔拉納基山': 'Mount Taranaki', '普克庫拉公園': 'Pukekura Park', '新普利茅斯海岸步道': 'New Plymouth Coastal Walkway', '埃格蒙特角燈塔': 'Cape Egmont Lighthouse',
    '旺格努伊河': 'Whanganui River', '旺格努伊玻璃藝術': 'Whanganui Glass Quarter', '馬納瓦圖峽谷': 'Manawatū Gorge', '帕默斯頓北廣場': 'Palmerston North Square',
    '蒂帕帕博物館': 'Te Papa Museum', '惠靈頓纜車': 'Wellington Cable Car', '維塔工作室': 'Weta Workshop', '古巴街': 'Cuba Street',
    '亞伯塔斯曼國家公園': 'Abel Tasman National Park', '黃金灣': 'Golden Bay', '卡胡朗伊國家公園': 'Kahurangi National Park', '莫圖伊卡': 'Motueka',
    '紐西蘭地理中心點': 'Centre of New Zealand', '塔胡納努伊海灘': 'Tahunanui Beach', '世界穿戴藝術博物館': 'World of WearableArt Museum', '尼爾森湖區': 'Nelson Lakes',
    '馬爾堡峽灣': 'Marlborough Sounds', '夏洛特女王步道': 'Queen Charlotte Track', '皮克頓港': 'Picton Harbour', '布倫海姆酒莊': 'Blenheim wineries',
    '法蘭茲約瑟夫冰河': 'Franz Josef Glacier', '薄餅岩': 'Pancake Rocks', '霍基蒂卡峽谷': 'Hokitika Gorge', '福克斯冰河': 'Fox Glacier',
    '庫克山': 'Aoraki / Mount Cook', '特卡波湖好牧羊人教堂': 'Church of the Good Shepherd', '基督城植物園': 'Christchurch Botanic Gardens', '班克斯半島': 'Banks Peninsula',
    '皇后鎮天際纜車': 'Skyline Gondola Queenstown', '瓦納卡湖': 'Lake Wānaka', '但尼丁火車站': 'Dunedin Railway Station', '奧塔哥半島': 'Otago Peninsula',
    '米爾福德峽灣': 'Milford Sound', '蒂阿瑙湖': 'Lake Te Anau', '峽灣國家公園': 'Fiordland National Park', '斯圖爾特島': 'Stewart Island',

    # ── 祭典 ──
    '懷唐伊日慶典': 'Waitangi Day', '奧克蘭燈光節': 'Auckland Lantern Festival', '哈比屯啤酒節': 'Hobbiton Beer Festival',
    '塔朗加爵士音樂節': 'Tauranga Jazz Festival', '節奏與葡萄藤音樂節': 'Rhythm & Vines Festival', '納皮爾裝飾藝術週末': 'Napier Art Deco Weekend',
    '塔拉納基花園節': 'Taranaki Garden Spectacular', '旺格努伊復古週末': 'Whanganui Vintage Weekend', '惠靈頓美食節': 'Wellington On a Plate',
    '莫圖伊卡鄉村市集': 'Motueka Sunday Market', '尼爾森藝術節': 'Nelson Arts Festival', '馬爾堡葡萄酒節': 'Marlborough Wine & Food Festival',
    '霍基蒂卡野生美食節': 'Hokitika Wildfoods Festival', '基督城街頭藝人節': 'Christchurch Buskers Festival', '皇后鎮冬季嘉年華': 'Queenstown Winter Festival',
    '布拉夫生蠔節': 'Bluff Oyster Festival',

    # ── 等級 ──
    '未踏之旅人': 'Untrodden Traveler', '旅行初心者': 'First-Time Traveler', '觀光旅客': 'Sightseer',
    '紐西蘭探索者': 'Aotearoa Explorer', '文化踐行者': 'Culture Practitioner', '旅遊達人': 'Travel Expert',
    '中土行者': 'Middle-earth Walker', '大區獵人': 'Region Hunter', '紐西蘭制霸者': 'Aotearoa Conqueror', '傳說的旅人': 'Legendary Traveler',

    # ── 成就分類 ──
    '全部': 'All', '絕景': 'Scenery', '美食': 'Food', '文化': 'Culture', '自然': 'Nature', '運動': 'Sports', '影劇': 'Film & TV', '旅程': 'Journey',

    # ── 成就名稱與條件 ──
    '三大名峰': 'Three Great Peaks', '庫克山・塔拉納基・阿斯派靈皆「遊玩」以上': "Aoraki, Taranaki & Aspiring all at 'Sightseeing' or above",
    '暗夜星空': 'Dark Sky Reserve', '特卡波湖所在的坎特伯雷「住宿」以上': "Stay or above in Canterbury (Lake Tekapo)",
    '地熱仙境': 'Geothermal Wonderland', '羅托魯瓦所在的豐盛灣「遊玩」以上': "Sightseeing in Bay of Plenty (Rotorua)",
    '峽灣之王': 'King of the Fiords', '米爾福德峽灣所在的南地「遊玩」以上': "Sightseeing in Southland (Milford Sound)",
    '黃金海灣': 'Golden Bay', '亞伯塔斯曼所在的塔斯曼「遊玩」以上': "Sightseeing in Tasman (Abel Tasman)",
    '冰河壯景': 'Glacier Country', '西海岸法蘭茲約瑟夫與福克斯冰河「遊玩」以上': "Sightseeing on the West Coast glaciers",
    '碧湖之鏡': 'Mirror of the Lake', '瓦納卡湖所在的奧塔哥「遊玩」以上': "Sightseeing in Otago (Lake Wānaka)",
    '四方極點': 'Four Extremes of Aotearoa', '北・東・西・南四端皆「途經」以上': "Visit all four cardinal extremes of NZ",
    '布拉夫生蠔': 'Bluff Oysters', '布拉夫生蠔節所在的南地「遊玩」以上': "Sightseeing in Southland (Bluff)",
    '長相思之鄉': 'Sauvignon Country', '馬爾堡「遊玩」以上': "Sightseeing in Marlborough",
    '黑皮諾之心': 'Heart of Pinot Noir', '中奧塔哥所在的奧塔哥「遊玩」以上': "Sightseeing in Otago (Central Otago)",
    '野生美食節': 'Wildfoods Festival', '霍基蒂卡野生美食節所在的西海岸「遊玩」以上': "Sightseeing on the West Coast (Hokitika)",
    '咖啡之都': 'Coffee Capital', '惠靈頓＋奧克蘭皆「遊玩」以上': "Sightseeing in both Wellington and Auckland",
    '莓果之鄉': 'Berry Country', '霍克斯灣「遊玩」以上': "Sightseeing in Hawke's Bay",
    '農場餐桌': 'Farm-to-Table', '懷卡托「遊玩」以上': "Sightseeing in Waikato",
    '毛利文化之心': 'Heart of Māori Culture', '豐盛灣＋北地皆「遊玩」以上': "Sightseeing in both Bay of Plenty and Northland",
    '毛利新年': 'Māori New Year', '毛利文化重鎮「住宿」以上，且手動勾選': 'Stay or above in a Māori heartland, manually claimed',
    '首都巡禮': 'Capital Calling', '惠靈頓「住宿」以上': 'Stay or above in Wellington',
    '帆船之都': 'City of Sails', '奧克蘭「遊玩」以上': 'Sightseeing in Auckland',
    '花園城市': 'Garden City', '基督城所在的坎特伯雷「遊玩」以上': "Sightseeing in Canterbury (Christchurch)",
    '裝飾藝術之城': 'Art Deco City', '納皮爾所在的霍克斯灣「遊玩」以上': "Sightseeing in Hawke's Bay (Napier)",
    '蘇格蘭之魂': 'Scottish Soul', '但尼丁所在的奧塔哥「遊玩」以上': "Sightseeing in Otago (Dunedin)",
    '四城巡禮': 'Four Cities Tour', '奧克蘭・惠靈頓・基督城・但尼丁皆「遊玩」以上': 'Sightseeing in all four main cities',
    '穿戴藝術': 'Wearable Art', '世界穿戴藝術博物館所在的尼爾森「遊玩」以上': "Sightseeing in Nelson (WoW Museum)",
    '螢火蟲洞': 'Glowworm Cave', '懷托摩所在的懷卡托「遊玩」以上': "Sightseeing in Waikato (Waitomo)",
    '觀鯨勝地': 'Whale Watching', '凱庫拉所在的坎特伯雷「遊玩」以上': "Sightseeing in Canterbury (Kaikōura)",
    '海豚共遊': 'Swim with Dolphins', '馬爾堡＋豐盛灣皆「遊玩」以上': 'Sightseeing in both Marlborough and Bay of Plenty',
    '塘鵝崖': 'Gannet Colony', '拐子角塘鵝棲息地所在的霍克斯灣「遊玩」以上': "Sightseeing in Hawke's Bay (Cape Kidnappers)",
    '黃眼企鵝': 'Yellow-Eyed Penguin', '奧塔哥半島所在的奧塔哥「遊玩」以上': "Sightseeing in Otago (Otago Peninsula)",
    '奇異鳥之家': 'Home of the Kiwi', '斯圖爾特島所在的南地「遊玩」以上': "Sightseeing in Southland (Stewart Island)",
    '極限首都': 'Adventure Capital', '皇后鎮所在的奧塔哥「遊玩」以上': "Sightseeing in Otago (Queenstown)",
    '步道之國': 'Land of Great Walks', '5 大區以上「遊玩」以上': 'Sightseeing in 5 or more regions',
    '滑雪雙峰': 'Twin Peaks Ski', '皇后鎮＋坎特伯雷皆「遊玩」以上': 'Sightseeing in both Otago and Canterbury',
    '衝浪海岸': 'Surf Coast', '吉斯伯恩＋塔拉納基皆「遊玩」以上': 'Sightseeing in both Gisborne and Taranaki',
    '皮划艇峽灣': 'Kayak the Sounds', '塔斯曼＋馬爾堡皆「遊玩」以上': 'Sightseeing in both Tasman and Marlborough',
    '夏爾故鄉': 'Home of the Shire', '哈比屯所在的懷卡托「遊玩」以上': "Sightseeing in Waikato (Hobbiton)",
    '中土三部曲': 'Middle-earth Trilogy', '哈比屯・維塔工坊・庫克山皆「遊玩」以上': "Sightseeing at Hobbiton, Weta & Aoraki",
    '維塔工坊': 'Weta Workshop', '惠靈頓「遊玩」以上': 'Sightseeing in Wellington',
    '最後的武士': 'The Last Samurai', '塔拉納基外景地「遊玩」以上': "Sightseeing in Taranaki (film location)",
    '首站之旅': 'First Stop', '造訪 1 個大區': 'Visit 1 region',
    '五區之旅': 'Five Regions', '造訪 5 個大區': 'Visit 5 regions',
    '十區之旅': 'Ten Regions', '造訪 10 個大區': 'Visit 10 regions',
    '十四區之旅': 'Fourteen Regions', '造訪 14 個大區': 'Visit 14 regions',
    '北島制霸': 'North Island Domination', '北島九區皆「遊玩」以上': 'All 9 North Island regions at Sightseeing or above',
    '南島制霸': 'South Island Domination', '南島七區皆「遊玩」以上': 'All 7 South Island regions at Sightseeing or above',
    '全境制霸': 'Aotearoa Domination', '16 大區皆「遊玩」以上，且手動勾選': 'All 16 regions at Sightseeing or above, manually claimed',
    '長居愛好者': 'Home Away from Home', '5 大區以上「長居」': 'Long-stay in 5 or more regions',
    '島嶼縱貫': 'Island Crossing', '北地→惠靈頓皆「途經」以上': "Northland to Wellington, both at 'Passing' or above",
    '南島縱貫': 'South Island Crossing', '塔斯曼→坎特伯雷→南地皆「途經」以上': "Tasman, Canterbury & Southland at 'Passing' or above",

    # ── 首頁成就預覽卡 ──
    '· 庫克山・塔拉納基・阿斯派靈': '· Aoraki · Taranaki · Aspiring',
    '· 馬塔里基七姊妹（手動勾選）': '· Matariki star cluster (manual)',
    '· 哈比屯・維塔・庫克山': '· Hobbiton · Weta · Aoraki',
    '· 北島＋南島（手動勾選）': '· North + South Island (manual)',
    '+18 分': '+18 pts',

    # ── 其他特化 ──
    '搜尋大區（中文／英文／地區）': 'Search regions (Chinese / English / Region)',
    '例：我的南島環島之旅、皇后鎮週末': 'e.g. My South Island road trip, Queenstown weekend',
    '識別碼　例：NZL-A3K9': 'Map code  e.g. NZL-A3K9',
    '點選大區，認識紐西蘭': 'Click a region to learn about New Zealand',
    '在地圖上點選大區，右側面板會顯示在地美食、景點與祭典介紹。': 'Click a region on the map and the panel shows its food, sights and festivals.',

    # ── 日本版原有 en 缺口（t() 鍵未收錄，補全）──
    ' · 未造訪': ' · Not visited',
    ' 大區已評分': ' regions rated',
    '— 由「紐西蘭制霸地圖」純靜態版產生 —': '— Generated by the New Zealand Conquest Map (static build) —',
    '平均 ': 'avg ',
    '識別碼 ': 'Map code ',
    '解鎖成就': 'Achievements unlocked',
    '造訪大區': 'Regions visited',
    '當前制霸等級': 'Current Conquest Level',
    '」（': ' (code ',
    '）的全部旅程紀錄與成就將從本機刪除，無法復原。建議先匯出備份。': ') — all trips and achievements will be deleted permanently. Export a backup first.',
    '在大區面板按下「☆ 想去」收藏，或在地圖上點選找靈感。': 'tap "☆ Want to go" in a region panel, or pick one from the map.',
}
