# -*- coding: utf-8 -*-
# 俄羅斯制霸地圖 — 資料模組 B（主體 43-83）

P_B = {
43: ('バシコルトスタン共和国','巴什科爾托斯坦共和國','伏爾加',
    ('烏拉爾山麓的共和國，薩拉瓦特與蜂蜜之鄉。','ウラル山麓の共和国、サラヴァトと蜂蜜の郷。','Ural foothill republic, land of Salavat Yulaev and honey.'),
    [('巴什基爾蜂蜜','バシキールのはちみつ','Bashkir honey'),('巴什基爾餃子','バシキール風ペリメニ','Bashkir pelmeni'),('查克查克甜點','チャクチャク','chak-chak')],
    [('烏法市阿吉特清真寺','ウファのリャリャ・チューリパン・モスク','Lala Tulpan Mosque in Ufa'),('薩拉瓦特紀念碑','サラヴァト・ユラーエフ像','Salavat Yulaev Monument'),('什爾甘-塔什洞穴','シュルガンタシュ洞窟','Shulgan-Tash cave'),('加富里洞穴','カポワ洞窟','Kapova cave paintings')],
    [('蜂蜜節','ハチミツ祭り','Honey Festival'),('民族日','民族の日','Republic Day')]),
44: ('マリ・エル共和国','馬里埃爾共和國','伏爾加',
    ('伏爾加支流的森林共和國，馬里民族的橡樹林。','ヴォルガ支流の森の共和国、マリ民族の聖なる林。','Forest republic on the Volga tributaries, sacred groves of the Mari people.'),
    [('馬里烤肉','マリ風シャシリク','Mari shashlik'),('橡樹蜜','菩提樹のはちみつ','linden honey'),('克瓦斯','クヴァス','kvass')],
    [('約什卡爾奧拉市中心','ヨシュカル・オラ中心部','Yoshkar-Ola embankment'),('布魯斯尼奇內森林','ブルスニチヌイの森','Brusnichny forest'),('馬里民族博物館','マリ民族博物館','Mari Ethnographic Museum'),('謝列傑爾湖','セレゲル湖','Lake Selegur')],
    [('馬里民族節','マリ民族祭り','Mari National Festival'),('城市日','市の日','City Day')]),
45: ('モルドヴィア共和国','莫爾多瓦共和國','伏爾加',
    ('伏爾加中游的芬蘭-烏戈爾民族共和國。','ヴォルガ中流のフィン・ウゴル民族の共和国。','Finno-Ugric republic of the middle Volga.'),
    [('莫爾多瓦餡餅','モルドヴィア風パイ','Mordovian pies'),('酸奶油燉肉','スメタナ煮込み','smetana stew'),('蜂蜜飲品','はちみつドリンク','honey drink')],
    [('薩蘭斯克千禧廣場','サランスクのミレニアム広場','Saransk Millennium Square'),('烏沙科夫紀念教堂','ウシャコフ記念大聖堂','Ushakov Memorial Cathedral'),('莫爾多瓦民族村','モルドヴィア民族村','Mordovian ethnic village'),('世界盃球場','モルドヴィア・アリーナ','Mordovia Arena')],
    [('民族節','民族祭り','National Festival'),('城市日','市の日','City Day')]),
46: ('タタールスタン共和国','韃靼斯坦共和國','伏爾加',
    ('喀山克里姆林宮，韃靼與俄羅斯文明的交會。','カザン・クレムリン、タタールとロシア文明の交差点。','Kazan Kremlin — where Tatar and Russian civilizations meet.'),
    [('查克查克','チャクチャク','chak-chak'),('喀山餃子','カザン風ペリメニ','Kazan pelmeni'),('埃奇波奇馬克餡餅','エチュポチュマク','echpochmak')],
    [('喀山克里姆林宮','カザン・クレムリン','Kazan Kremlin'),('庫爾沙里夫清真寺','クル・シャリフ・モスク','Kul Sharif Mosque'),('鮑曼步行街','バウマン通り','Bauman Street'),('斯維亞日斯克島','スヴィヤシュスク島','Sviyazhsk island')],
    [('喀山城市日','カザン市の日','Kazan City Day'),('韃靼民族節','タタール民族祭り','Sabantuy festival')]),
47: ('ウドムルト共和国','烏德穆爾特共和國','伏爾加',
    ('柴可夫斯基誕生之地，AK-47的故鄉。','チャイコフスキー生誕の地、AK-47の故郷。','Birthplace of Tchaikovsky and home of the AK-47.'),
    [('烏德穆爾特餃子','ウドムルト風ペリメニ','Udmurt pelmeni'),('越橘果醬','リンゴンベリージャム','lingonberry jam'),('克拉希爾湯','ウドムルトのスープ','Udmurt soup')],
    [('柴可夫斯基故居博物館','チャイコフスキー記念館（ヴォトキンスク）','Tchaikovsky House in Votkinsk'),('卡拉什尼科夫博物館','カラシニコフ博物館','Kalashnikov Museum in Izhevsk'),('伊熱夫斯克武器廣場','イジェフスクの武器広場','Izhevsk weapons square'),('自然公園內奇金卡','ネチキンカ自然公園','Nechkinsky National Park')],
    [('柴可夫斯基音樂節','チャイコフスキー音楽祭','Tchaikovsky Festival'),('城市日','市の日','City Day')]),
48: ('チュヴァシ共和国','楚瓦什共和國','伏爾加',
    ('伏爾加河畔的楚瓦什民族，伏爾加保加利亞後裔。','ヴォルガ川のチュヴァシ民族、ヴォルガ・ブルガールの末裔。','Chuvash people of the Volga, descendants of Volga Bulgaria.'),
    [('楚瓦什烤肉','チュヴァシ風シャシリク','Chuvash shashlik'),('楚瓦什餡餅','チュヴァシ・パイ','Chuvash pies'),('蜂蜜酒','蜂蜜酒','honey drink')],
    [('切博克薩雷伏爾加堤岸','チェボクサルイ堤防','Cheboksary Volga embankment'),('楚瓦什民族博物館','チュヴァシ民族博物館','Chuvash National Museum'),('紅教堂','赤い教会','Red Church'),('伏爾加河遊船','ヴォルガ川クルーズ','Volga cruise')],
    [('楚瓦什民族節','チュヴァシ民族祭り','Chuvash National Festival'),('城市日','市の日','City Day')]),
49: ('キーロフ州','基洛夫州','伏爾加',
    ('維亞特卡河畔的木造之都，迪姆科沃玩具。','ヴャトカ川の木造の街、ディムコヴォ人形。','Wooden capital on the Vyatka, home of Dymkovo toys.'),
    [('基洛夫麵包圈','キーロフのブーブリク','Kirov baranki'),('迪姆科沃甜點','ディムコヴォ菓子','Dymkovo pastry'),('野生莓果','ベリー','wild berries')],
    [('聖謝拉菲姆教堂','セラフィム教会','St Seraphim Church'),('維亞特卡河堤','ヴャトカ川の堤防','Vyatka embankment'),('迪姆科沃玩具博物館','ディムコヴォ人形博物館','Dymkovo Toy Museum'),('亞歷山大花園','アレクサンドル庭園','Alexander Garden')],
    [('城市日','市の日','City Day'),('手工藝節','工芸祭り','Craft Festival')]),
50: ('ニジニ・ノヴゴロド州','下諾夫哥羅德州','伏爾加',
    ('伏爾加與奧卡河交會，高爾基的故鄉。','ヴォルガとオカの合流点、ゴーリキーの故郷。','Where the Volga meets the Oka, hometown of Maxim Gorky.'),
    [('下諾夫哥羅德烤餅','ニジニの焼きパイ','Nizhny pies'),('魚湯','ウハー','ukha fish soup'),('蜂蜜格瓦斯','ハチミツクヴァス','honey kvass')],
    [('下諾夫哥羅德克里姆林宮','ニジニ・ノヴゴロド・クレムリン','Nizhny Novgorod Kremlin'),('高爾基故居','ゴーリキー記念館','Gorky House Museum'),('大波克羅夫卡步行街','大ポクロフカ通り','Bolshaya Pokrovskaya Street'),('契卡洛夫階梯','チカロフ階段','Chkalov Staircase')],
    [('城市日','市の日','City Day'),('高爾基文學節','ゴーリキー文学祭','Gorky Literary Festival')]),
51: ('オレンブル克州','奧倫堡州','伏爾加',
    ('歐洲與亞洲交界，奧倫堡披肩之鄉。','欧州とアジアの境界、オレンブルクのショールの郷。','Border of Europe and Asia, famous for Orenburg shawls.'),
    [('奧倫堡麵包圈','オレンブルクのブーブリク','Orenburg baranki'),('巴什基爾蜂蜜','バシキールのはちみつ','Bashkir honey'),('羊肉湯','羊肉のスープ','lamb soup')],
    [('歐洲-亞洲界碑','欧州アジア境界のオベリスク','Europe-Asia obelisk'),('奧倫堡披肩博物館','オレンブルク・ショール博物館','Orenburg Shawl Museum'),('卡拉萬薩拉伊','カラヴァンサライ','Caravanserai'),('烏拉爾河','ウラル川','Ural river')],
    [('披肩節','ショール祭り','Shawl Festival'),('城市日','市の日','City Day')]),
52: ('ペンザ州','奔薩州','伏爾加',
    ('伏爾加高原的文學與鐵路之城。','ヴォルガ高地の文学と鉄道の街。','Literary and railway city of the Volga uplands.'),
    [('奔薩蜂蜜蛋糕','ペンザの蜂蜜ケーキ','Penza honey cake'),('蘑菇湯','キノコスープ','mushroom soup'),('酸奶油薄餅','スメタナパンケーキ','smetana pancakes')],
    [('奔薩蘇聯時光廣場','ペンザのスターリン様式広場','Penza central square'),('萊蒙托夫莊園','レールモントフ記念館','Lermontov Estate in Tarkhany'),('果戈理大街','ゴーゴリ通り','Gogol Street'),('蘇拉河堤','スーラ川の堤防','Sura river embankment')],
    [('城市日','市の日','City Day'),('文學節','文学祭り','Literary Festival')]),
53: ('サマラ州','薩馬拉州','伏爾加',
    ('伏爾加河畔的太空之都，蘇聯火箭的搖籃。','ヴォルガ川の宇宙の都、ソ連ロケットの揺り籠。','Space capital on the Volga, cradle of Soviet rocketry.'),
    [('薩馬拉啤酒','サマラ・ビール','Zhigulevskoye beer'),('烤餡餅','焼きピロシキ','baked pirozhki'),('伏爾加魚子','ヴォルガのキャビア','Volga caviar')],
    [('薩馬拉太空博物館','サマラ宇宙博物館','Samara Space Museum'),('伏爾加河堤','ヴォルガ川の堤防','Samara embankment'),('斯大林碉堡','スターリン・バンカー','Stalin Bunker'),('日古列夫山','ジグリ山','Zhiguli hills')],
    [('城市日','市の日','City Day'),('太空節','宇宙祭り','Space Festival')]),
54: ('サラトフ州','薩拉托夫州','伏爾加',
    ('伏爾加河畔的大學之城，加加林的降落之地。','ヴォルガ川の大学都市、ガガーリンの着陸地。','University city on the Volga, where Gagarin landed.'),
    [('薩拉托夫麵包','サラトフのパン','Saratov bread'),('伏爾加烤魚','ヴォルガの焼き魚','grilled Volga fish'),('果醬卷','ジャムロール','jam roll')],
    [('加加林降落紀念碑','ガガーリン着陸記念碑','Gagarin Landing Monument'),('薩拉托夫音樂廳','サラトフ音楽堂','Saratov Conservatory'),('伏爾加河大橋','ヴォルガ橋','Saratov Bridge'),('舊信者教堂','古儀式派教会','Old Believers churches')],
    [('城市日','市の日','City Day'),('宇航日','宇宙飛行士の日','Cosmonautics Day')]),
55: ('ウリヤノフ斯克州','烏里揚諾夫斯克州','伏爾加',
    ('列寧的故鄉辛比爾斯克，伏爾加河畔。','レーニン生誕の地シンビルスク、ヴォルガ川のほとり。','Simbirsk, birthplace of Lenin on the Volga.'),
    [('烏里揚諾夫斯克麵包圈','ウリヤノフスクのブーブリク','Ulyanovsk baranki'),('烤魚','焼き魚','grilled fish'),('野莓果醬','ベリージャム','berry jam')],
    [('列寧故居博物館','レーニン記念館','Lenin House Museum'),('岡察洛夫故居','ゴンチャロフ記念館','Goncharov House'),('伏爾加河纜車','ヴォルガのロープウェイ','Volga cable car'),('舊辛比爾斯克街區','旧シンビルスク街並み','Old Simbirsk quarter')],
    [('城市日','市の日','City Day'),('歷史節','歴史祭り','History Festival')]),
56: ('ペルミ地方','彼爾姆邊疆區','伏爾加',
    ('烏拉爾西麓的工業與芭蕾之城，昆古爾冰洞。','ウラル西麓の産業とバレエの街、クングルの氷の洞窟。','Industrial and ballet city west of the Urals, home of Kungur Ice Cave.'),
    [('佩利梅尼餃子','ペリメニ','pelmeni'),('烏拉爾烤肉','ウラル風シャシリク','Ural shashlik'),('蜂蜜酒','蜂蜜酒','honey drink')],
    [('昆古爾冰洞','クングルの氷の洞窟','Kungur Ice Cave'),('彼爾姆歌劇院','ペルミ歌劇場','Perm Opera House'),('彼爾姆木造神像博物館','ペルミの木彫り神像','Perm wooden sculpture museum'),('卡馬河堤','カマ川の堤防','Kama river embankment')],
    [('城市日','市の日','City Day'),('冰洞節','氷の洞窟祭り','Ice Cave Festival')]),
57: ('クルガン州','庫爾干州','烏拉爾',
    ('西伯利亞鐵路途經的草原之州。','シベリア鉄道が通る草原の州。','Steppe region on the Trans-Siberian Railway.'),
    [('庫爾干香腸','クルガンソーセージ','Kurgan sausage'),('蕎麥粥','そば粥','buckwheat kasha'),('樺樹汁','白樺の樹液','birch sap')],
    [('庫爾干中央廣場','クルガン中央広場','Kurgan central square'),('救世主大教堂','救世主大聖堂','Savior Cathedral'),('托博爾河','トボル川','Tobol river'),('西伯利亞鐵路紀念碑','シベリア鉄道記念碑','Trans-Siberian railway monument')],
    [('城市日','市の日','City Day'),('草原節','草原祭り','Steppe Festival')]),
58: ('スヴェルドロフ斯克州','斯維爾德洛夫斯克州','烏拉爾',
    ('葉卡捷琳堡，烏拉爾之都與歐亞界碑。','エカテリンブルク、ウラルの都と欧亜境界碑。','Yekaterinburg, the Ural capital and the Europe-Asia border.'),
    [('烏拉爾餃子','ウラル風ペリメニ','Ural pelmeni'),('肉凍','アスピック','kholodets'),('蜂蜜蛋糕','蜂蜜ケーキ','honey cake')],
    [('滴血教堂（葉卡捷琳堡）','血の上の教会（エカテリンブルク）','Church on the Blood'),('歐亞界碑','欧亜境界碑','Europe-Asia boundary marker'),('葉卡捷琳堡歌劇院','エカテリンブルク歌劇場','Yekaterinburg Opera'),('涅維揚斯克斜塔','ネヴィヤンスク斜塔','Nevyansk leaning tower')],
    [('城市日','市の日','City Day'),('鐵路節','鉄道祭り','Railway Festival')]),
59: ('チュメニ州','秋明州','烏拉爾',
    ('西伯利亞的門戶，俄羅斯最早的西伯利亞城市。','シベリアの玄関、最初のシベリアの都市。','Gateway to Siberia, the first Russian city in Siberia.'),
    [('秋明餃子','チュメニ風ペリメニ','Tyumen pelmeni'),('熱泉煮蛋','温泉卵','hot-spring eggs'),('西伯利亞魚湯','シベリアのウハー','Siberian fish soup')],
    [('熱泉療養地','温泉リゾート','Tyumen hot springs'),('秋明克里姆林宮','チュメニのクレムリン','Tyumen Kremlin complex'),('木造商人街','木造商人の家並み','Wooden merchant houses'),('托博爾斯克克里姆林宮','トボリスク・クレムリン','Tobolsk Kremlin')],
    [('熱泉節','温泉祭り','Hot Spring Festival'),('城市日','市の日','City Day')]),
60: ('チェリャビンス克州','車里雅賓斯克州','烏拉爾',
    ('坦克之城，烏拉爾山脈南麓的工業重鎮。','タンクの街、ウラル山脈南麓の工業都市。','Tank capital south of the Ural Mountains.'),
    [('車里雅賓斯克烤肉','チェリャビンスク風シャシリク','Chelyabinsk shashlik'),('烏拉爾餃子','ペリメニ','pelmeni'),('酸奶油薄餅','スメタナパンケーキ','smetana pancakes')],
    [('阿廖沙紀念像','オルロフの像','Alyosha monument'),('車里雅賓斯克舞蹈劇場','チェリャビンスク・ダンス劇場','Chelyabinsk Drama Theatre'),('斯莫利諾湖','スモリノ湖','Lake Smolino'),('塔甘奈國家公園','タガナイ国立公園','Taganay National Park')],
    [('城市日','市の日','City Day'),('坦克節','戦車祭り','Tank Festival')]),
61: ('ハンティ・マンシ自治管区','漢特-曼西自治區','烏拉爾',
    ('石油之都，鄂畢河與漢特民族。','石油の都、オビ川とハンティ民族。','Oil capital on the Ob, land of the Khanty people.'),
    [('鄂畢河魚湯','オビ川の魚スープ','Ob river fish soup'),('馴鹿肉排','トナカイステーキ','reindeer steak'),('松子','松の実','pine nuts')],
    [('漢特-曼西斯克市中心','ハンティ・マンシースク中心部','Khanty-Mansiysk centre'),('民族露天博物館','野外民族博物館','Torum Maa open-air museum'),('鄂畢河','オビ川','Ob river'),('石油博物館','石油博物館','Oil Museum')],
    [('漢特民族節','ハンティ民族祭り','Khanty National Festival'),('城市日','市の日','City Day')]),
62: ('ヤマロ・ネネツ自治管区','亞馬爾-涅涅茨自治區','烏拉爾',
    ('世界最北的天然氣田，凍原上的馴鹿之國。','世界最北のガス田、ツンドラのトナカイの国。','Northernmost gas fields, reindeer country of the tundra.'),
    [('馴鹿肉湯','トナカイのスープ','reindeer soup'),('凍原莓果','ツンドラのベリー','tundra berries'),('魚乾','干し魚','dried fish')],
    [('薩列哈爾德市','サレハルド','Salekhard'),('凍原與馴鹿牧場','ツンドラのトナカイ牧場','Tundra reindeer herding'),('北極圈界碑','北極圏の標識','Arctic Circle marker'),('鄂畢河灣','オビ湾','Gulf of Ob')],
    [('馴鹿牧民日','トナカイ遊牧民の日','Reindeer Herders Day'),('極夜節','極夜祭り','Polar Night Festival')]),
63: ('アルタイ地方','阿爾泰邊疆區','西伯利亞',
    ('巴爾瑙爾與比斯克，西伯利亞南部的糧倉。','バルナウルとビイスク、シベリア南部の穀倉。','Barnaul and Biysk, the granary of southern Siberia.'),
    [('阿爾泰蜂蜜','アルタイのはちみつ','Altai honey'),('阿爾泰奶酪','アルタイチーズ','Altai cheese'),('西伯利亞餃子','シベリア風ペリメニ','Siberian pelmeni')],
    [('巴爾瑙爾市區','バルナウル中心部','Barnaul city centre'),('貝洛庫里哈療養地','ベロクリハ','Belokurikha resort'),('比斯克舊城','ビイスク旧市街','Biysk old town'),('卡通河','カトゥン川','Katun river')],
    [('城市日','市の日','City Day'),('蜂蜜節','ハチミツ祭り','Honey Festival')]),
64: ('アルタイ共和国','阿爾泰共和國','西伯利亞',
    ('金山阿爾泰，烏科克高原與雪豹之地。','黄金の山アルタイ、ウコク高原とユキヒョウの地。','The Golden Mountains of Altai — Ukok Plateau and snow leopards.'),
    [('阿爾泰山區蜂蜜','アルタイ山岳はちみつ','Altai mountain honey'),('阿爾泰燉羊肉','アルタイ風羊肉煮込み','Altai lamb stew'),('松子','松の実','pine nuts')],
    [('捷列茨科耶湖','テレツコエ湖','Lake Teletskoye'),('烏科克高原','ウコク高原','Ukok Plateau'),('阿爾泰國家公園','アルタイ自然保護区','Altai Nature Reserve'),('卡通河谷','カトゥン川渓谷','Katun valley')],
    [('阿爾泰民族節','アルタイ民族祭り','Altai National Festival'),('馴鹿牧民日','遊牧民の日','Herdsmen Festival')]),
65: ('イルクーツ克州','伊爾庫茨克州','西伯利亞',
    ('西伯利亞的巴黎，貝加爾湖的門戶。','シベリアのパリ、バイカル湖の玄関。','The Paris of Siberia, gateway to Lake Baikal.'),
    [('貝加爾湖歐姆魚','バイカルのオームリ','Baikal omul fish'),('布利亞特餃子','ブリヤート風餃子','Buryat buuzy dumplings'),('樺樹汁','白樺の樹液','birch sap')],
    [('貝加爾湖','バイカル湖','Lake Baikal'),('利斯特維揚卡','リストヴィャンカ','Listvyanka'),('伊爾庫茨克木造街區','イルクーツクの木造街並み','Irkutsk wooden houses'),('130 街區','130クォーター','130 Quarter')],
    [('貝加爾冰上節','バイカル氷上祭り','Baikal Ice Festival'),('城市日','市の日','City Day')]),
66: ('ケメロヴォ州','克麥羅沃州','西伯利亞',
    ('庫茲巴斯煤田，西伯利亞的工業心臟。','クズバス炭田、シベリアの産業の心臓。','The Kuzbass coalfield, industrial heart of Siberia.'),
    [('庫茲巴斯烤肉','クズバス風シャシリク','Kuzbass shashlik'),('西伯利亞餃子','シベリア風ペリメニ','Siberian pelmeni'),('野生莓果','ベリー','wild berries')],
    [('克麥羅沃音樂劇場','ケメロヴォ音楽劇場','Kemerovo Musical Theatre'),('托木斯克河','トミ川','Tom river'),('舍列格什滑雪場','シェレゲシュ','Sheregesh ski resort'),('庫茲涅茨克堡壘','クズネツク要塞','Kuznetsk fortress')],
    [('城市日','市の日','City Day'),('礦工節','鉱夫の日','Miner Day')]),
67: ('クラスノヤルスク地方','克拉斯諾亞爾斯克邊疆區','西伯利亞',
    ('葉尼塞河與斯托爾貝巨石，西伯利亞的中心。','エニセイ川とストルブイ岩柱、シベリアの中心。','The Yenisei and Stolby rocks, centre of Siberia.'),
    [('克拉斯諾亞爾斯克蜂蜜','クラスノヤルスクのはちみつ','Krasnoyarsk honey'),('松子','松の実','pine nuts'),('西伯利亞魚湯','シベリアのウハー','Siberian fish soup')],
    [('斯托爾貝自然保護區','ストルブイ自然保護区','Stolby Nature Reserve'),('葉尼塞河','エニセイ川','Yenisei river'),('普托拉納高原','プトラナ高原','Putorana Plateau'),('帕拉斯科夫亞岩','パラスコヴィエ岩','Paraskeva rock chapel')],
    [('城市日','市の日','City Day'),('葉尼塞節','エニセイ祭り','Yenisei Festival')]),
68: ('ノヴォシビルスク州','新西伯利亞州','西伯利亞',
    ('西伯利亞的首都，俄羅斯第三大城。','シベリアの首都、ロシア第3の都市。','Capital of Siberia, Russias third-largest city.'),
    [('新西伯利亞餃子','ノヴォシビルスク風ペリメニ','Novosibirsk pelmeni'),('酸奶油薄餅','スメタナパンケーキ','smetana pancakes'),('西伯利亞莓果派','ベリーパイ','berry pie')],
    [('歌劇與芭蕾劇院','ノヴォシビルスク歌劇場','Novosibirsk Opera and Ballet Theatre'),('鄂畢河海','オビ海','Ob Sea reservoir'),('西伯利亞動物園','ノヴォシビルスク動物園','Novosibirsk Zoo'),('科學城','アカデムゴロドク','Akademgorodok')],
    [('城市日','市の日','City Day'),('歌劇節','オペラ祭り','Opera Festival')]),
69: ('オムスク州','鄂木斯克州','西伯利亞',
    ('額爾齊斯河畔的哥薩克之城，西伯利亞的古都。','イルティシュ川のコサックの街、シベリアの古都。','Cossack city on the Irtysh, old capital of Siberia.'),
    [('鄂木斯克魚湯','オムスクのウハー','Omsk fish soup'),('蜂蜜薑餅','蜂蜜ジンジャーブレッド','honey gingerbread'),('蕎麥粥','そば粥','buckwheat kasha')],
    [('鄂木斯克堡壘','オムスク要塞','Omsk fortress'),('圣母升天大教堂','生神女就寝大聖堂','Dormition Cathedral'),('額爾齊斯河堤','イルティシュ川の堤防','Irtysh embankment'),('西伯利亞民族博物館','シベリア民族博物館','Siberian Museum of Culture')],
    [('城市日','市の日','City Day'),('哥薩克節','コサック祭り','Cossack Festival')]),
70: ('トムスク州','托木斯克州','西伯利亞',
    ('西伯利亞的雅典，木造雕花建築之城。','シベリアのアテネ、木造彫刻建築の街。','The Athens of Siberia, city of carved wooden architecture.'),
    [('托木斯克蜂蜜','トムスクのはちみつ','Tomsk honey'),('西伯利亞餃子','シベリア風ペリメニ','Siberian pelmeni'),('松子蛋糕','松の実ケーキ','pine nut cake')],
    [('木造雕花建築群','木造彫刻建築群','Carved wooden houses of Tomsk'),('托木斯克國立大學','トムスク国立大学','Tomsk State University'),('拉蓋爾內花園','ラゲールヌイ庭園','Lagerny Garden'),('托姆河','トミ川','Tom river')],
    [('城市日','市の日','City Day'),('木造建築節','木造建築祭り','Wooden Architecture Festival')]),
71: ('トゥヴァ共和国','圖瓦共和國','西伯利亞',
    ('亞洲中心，呼麥喉音與草原的國度。','アジアの中心、ホーメイ（喉歌）と草原の国。','Centre of Asia, land of throat singing and steppe.'),
    [('圖瓦奶茶','トゥヴァのミルクティー','Tuvan milk tea'),('羊肉餃子','羊肉の餃子','mutton dumplings'),('奶酪乾','乾燥チーズ','dried cheese')],
    [('克孜勒亞洲中心碑','クズルのアジア中心オベリスク','Asia Centre obelisk in Kyzyl'),('烏布蘇盆地','ウヴス・ヌール盆地','Uvs Nuur Basin'),('圖瓦民族博物館','トゥヴァ民族博物館','Tuvan National Museum'),('葉尼塞河源頭','エニセイ川の源','Upper Yenisei')],
    [('呼麥音樂節','ホーメイ祭り','Throat Singing Festival'),('馴馬節','馬祭り','Horse Festival')]),
72: ('ハカス共和国','哈卡斯共和國','西伯利亞',
    ('葉尼塞河畔的草原，石雕紀念碑之國。','エニセイ川の草原、石彫記念碑の国。','Steppe on the Yenisei, land of ancient stone stelae.'),
    [('哈卡斯烤肉','ハカス風シャシリク','Khakas shashlik'),('酸馬奶','馬乳酒','kumis'),('草原奶酪','草原のチーズ','steppe cheese')],
    [('薩爾貝克古墓群','サルビク墳墓','Salbyk burial mounds'),('大薩爾貝克石雕','石彫の立像','Khakass stone stelae'),('阿巴坎市','アバカン','Abakan city'),('葉尼塞河','エニセイ川','Yenisei river')],
    [('民族節','民族祭り','Khakas National Festival'),('騎馬節','乗馬祭り','Equestrian Festival')]),
73: ('ザバイカリエ地方','外貝加爾邊疆區','西伯利亞',
    ('貝加爾以東的草原與森林，赤塔與達斡爾。','バイカル以東の草原と森、チタとダウリア。','Steppe and forest east of Baikal — Chita and Dauria.'),
    [('布里亞特餃子','ブリヤート風餃子','Buryat buuzy'),('草原羊肉','草原の羊肉','steppe lamb'),('松子','松の実','pine nuts')],
    [('赤塔市列寧廣場','チタの広場','Chita central square'),('達斡爾自然保護區','ダウルスキー自然保護区','Daurian Nature Reserve'),('外貝加爾國家公園','ザバイカル国立公園','Zabaikalsky National Park'),('科達爾山','コーダル山','Kodar mountains')],
    [('民族節','民族祭り','National Festival'),('城市日','市の日','City Day')]),
74: ('アムール州','阿穆爾州','遠東',
    ('黑龍江對岸的布拉戈維申斯克，太空城齊奧爾科夫斯基。','アムール川の向こうのブラゴヴェシチェンスク、宇宙都市ツィオルコフスキー。','Blagoveshchensk on the Amur and the space city Tsiolkovsky.'),
    [('阿穆爾魚湯','アムールの魚スープ','Amur fish soup'),('東方港蟹','カニ','Amur crab'),('野莓果醬','ベリージャム','berry jam')],
    [('阿穆爾河堤','アムール川の堤防','Amur river embankment'),('東方航天發射場','ボストチヌイ宇宙基地','Vostochny Cosmodrome'),('阿爾比諾石窟','アルビノの岩絵','Albino petroglyphs'),('布拉戈維申斯克老城','ブラゴヴェシチェンスク旧市街','Blagoveshchensk old town')],
    [('城市日','市の日','City Day'),('宇航節','宇宙祭り','Space Festival')]),
75: ('ブリヤート共和国','布里亞特共和國','遠東',
    ('貝加爾湖東岸，佛教的達桑寺廟。','バイカル湖東岸、仏教のダツァン寺院。','Eastern shore of Baikal, land of Buddhist datsans.'),
    [('布里亞特餃子','ブヤーズ（ブリヤート餃子）','Buryat buuzy'),('薩拉馬特粥','サラマト','salamat porridge'),('貝加爾歐姆魚','バイカルのオームリ','Baikal omul')],
    [('貝加爾湖東岸','バイカル湖東岸','Lake Baikal east shore'),('伊沃爾金斯基達桑寺','イヴォルギンスキー・ダツァン','Ivolginsky Datsan'),('烏蘭烏德列寧頭像','ウラン・ウデのレーニン像','Ulan-Ude Lenin head'),('阿爾尚溫泉','アルシャン温泉','Arshan hot springs')],
    [('阿爾塔里加節','アルタリガ','Altargana festival'),('白月節','白い月（サガールガン）','White Moon festival')]),
76: ('ユダヤ自治州','猶太自治州','遠東',
    ('遠東的比羅比詹，猶太文化自治州。','極東のビロビジャン、ユダヤ文化自治州。','Birobidzhan in the Far East, the Jewish autonomous region.'),
    [('猶太麵包','ユダヤ風パン','Jewish challah bread'),('阿穆爾魚湯','アムールの魚スープ','Amur fish soup'),('野莓果醬','ベリージャム','berry jam')],
    [('比羅比詹猶太教堂','ビロビジャンのシナゴーグ','Birobidzhan Synagogue'),('猶太文化博物館','ユダヤ文化博物館','Jewish Museum'),('比拉河','ビラ川','Bira river'),('猶太民族文化村','ユダヤ文化村','Jewish cultural village')],
    [('猶太文化節','ユダヤ文化祭り','Jewish Culture Festival'),('城市日','市の日','City Day')]),
77: ('カムチャツカ地方','堪察加邊疆區','遠東',
    ('火山與棕熊之國，間歇泉谷的遠東秘境。','火山と熊の国、間歇泉谷の秘境。','Land of volcanoes and bears, home of the Valley of Geysers.'),
    [('堪察加帝王蟹','カムチャツカのタラバガニ','Kamchatka king crab'),('紅鮭魚子','イクラ','red caviar'),('堪察加魚湯','カムチャツカのウハー','Kamchatka fish soup')],
    [('阿瓦恰火山','アバチャ火山','Avachinsky volcano'),('間歇泉谷','間歇泉谷','Valley of Geysers'),('庫里爾湖棕熊','クリル湖のヒグマ','Kuril Lake brown bears'),('彼得羅巴甫洛夫斯克港','ペトロパブロフスク・カムチャツキー','Petropavlovsk-Kamchatsky')],
    [('火山節','火山祭り','Volcano Festival'),('鮭魚節','サーモン祭り','Salmon Festival')]),
78: ('マガダン州','馬加丹州','遠東',
    ('科雷馬公路的終點，鄂霍次克海之港。','コルィマ街道の終点、オホーツク海の港。','End of the Kolyma Highway, port on the Sea of Okhotsk.'),
    [('馬加丹蟹','マガダンカニ','Magadan crab'),('紅鮭魚子','イクラ','red caviar'),('海膽','ウニ','sea urchin')],
    [('馬加丹海濱','マガダンの堤防','Magadan embankment'),('悲傷面具紀念碑','悲しみの仮面記念碑','Mask of Sorrow monument'),('科雷馬公路','コルィマ街道','Kolyma Highway'),('鄂霍次克海','オホーツク海','Sea of Okhotsk')],
    [('城市日','市の日','City Day'),('捕魚節','漁業祭り','Fishermen Day')]),
79: ('沿海地方','濱海邊疆區','遠東',
    ('海參崴，太平洋的終點與西伯利亞鐵路盡頭。','ウラジオストク、太平洋の終着駅。','Vladivostok — the Pacific terminus of the Trans-Siberian Railway.'),
    [('海參崴蟹','ウラジオストクのカニ','Vladivostok crab'),('扇貝','ホタテ','scallops'),('紅魚子醬','イクラ','red caviar')],
    [('金角灣與鷹巢山','金角湾と鷲の巣展望台','Golden Horn Bay and Eagle Nest Hill'),('俄羅斯島大橋','ルースキー島大橋','Russky Island Bridge'),('西伯利亞鐵路9288公里碑','シベリア鉄道終点標識','9288 km marker'),('濱海邊疆區海洋館','沿海州海洋水族館','Primorsky Aquarium')],
    [('城市日','市の日','Vladivostok City Day'),('太平洋艦隊節','太平洋艦隊の日','Pacific Fleet Day')]),
80: ('サハ共和国','薩哈共和國','遠東',
    ('世界最大的共和國，冷極奧伊米亞康與勒拿河柱。','世界最大の共和国、寒極オイミャコンとレナ川の柱。','The worlds largest republic — the cold pole Oymyakon and the Lena Pillars.'),
    [('薩哈馬肉乾','サハ風馬肉','Sakha horse meat'),('冷極魚湯','寒極の魚スープ','cold-pole fish soup'),('凍土莓果','凍土のベリー','permafrost berries')],
    [('勒拿河柱狀岩','レナの柱','Lena Pillars Nature Park'),('奧伊米亞康（冷極）','オイミャコン','Oymyakon, the cold pole'),('雅庫茨克猛獁象博物館','ヤクーツクのマンモス博物館','Yakutsk Mammoth Museum'),('通古斯河','トゥングースカ川','Tunguska river')],
    [('冷極慶典','寒極フェスティバル','Cold Pole Festival'),('雅庫特民族節','サハ民族祭り','Ysyakh festival')]),
81: ('サハリン州','薩哈林州','遠東',
    ('鄂霍次克海的魚島，俄羅斯最東的州。','オホーツク海の魚の島、ロシア最東端の州。','Island of fish on the Sea of Okhotsk, Russias easternmost region.'),
    [('薩哈林帝王蟹','サハリンのタラバガニ','Sakhalin king crab'),('鮭魚魚子','イクラ','salmon caviar'),('海膽','ウニ','sea urchin')],
    [('南薩哈林斯克市','ユジノサハリンスク','Yuzhno-Sakhalinsk'),('普希金塔展望台','プーシキン塔','Gorny Vozdukh ski resort'),('海豹角','海豹の岬','Cape of Seals'),('鄂霍次克海','オホーツク海','Sea of Okhotsk')],
    [('城市日','市の日','City Day'),('鮭魚節','サーモン祭り','Salmon Festival')]),
82: ('ハバロフ斯克地方','哈巴羅夫斯克邊疆區','遠東',
    ('黑龍江畔的遠東大城，阿穆爾河對岸就是中國。','アムール川の極東の大都市。','Far Eastern capital on the Amur, facing China across the river.'),
    [('遠東蟹','極東のカニ','Far East crab'),('紅魚子醬','イクラ','red caviar'),('黑龍江魚湯','アムールのウハー','Amur fish soup')],
    [('阿穆爾河堤','アムール川の堤防','Amur river embankment'),('哈巴羅夫斯克大橋','ハバロフスク橋','Khabarovsk Bridge'),('列寧廣場','レーニン広場','Lenin Square'),('穆拉維約夫-阿穆爾斯基紀念碑','ムラヴィヨフ・アムールスキー像','Muravyov-Amursky monument')],
    [('城市日','市の日','City Day'),('阿穆爾節','アムール祭り','Amur Festival')]),
83: ('チュクチ自治管区','楚科奇自治區','遠東',
    ('白令海峽對岸是阿拉斯加，極東的盡頭。','ベーリング海峡の向こうはアラスカ、極東の果て。','Across the Bering Strait from Alaska — the edge of the Far East.'),
    [('馴鹿肉湯','トナカイのスープ','reindeer soup'),('海象肉','セイウチ肉','walrus meat'),('凍原莓果','ツンドラのベリー','tundra berries')],
    [('白令海峽','ベーリング海峡','Bering Strait'),('弗蘭格爾島','ウランゲリ島','Wrangel Island'),('阿納德爾市','アナディリ','Anadyr'),('楚科奇海岸','チュクチ海岸','Chukotka coast')],
    [('馴鹿牧民日','トナカイ遊牧民の日','Reindeer Herders Day'),('極夜節','極夜祭り','Polar Night Festival')]),
}
