# -*- coding: utf-8 -*-
# 俄羅斯制霸地圖 — 資料模組 A（主體 1-42）
# 每筆：(ja名, zh名, 地區key, (tagline_zh, tagline_ja, tagline_en), food[(zh,ja,en)x3], spots[(zh,ja,en)x4], matsuri[(zh,ja,en)x2])

P_A = {
1: ('モスクワ市','莫斯科市','中央',
    ('克里姆林宮與紅場，俄羅斯的心臟。','クレムリンと赤の広場、ロシアの心臓部。','The Kremlin and Red Square — the heart of Russia.'),
    [('羅宋湯與酸奶油','ボルシチとサワークリーム','borscht with sour cream'),('黑麵包與鹽','黒パンと塩','black bread and salt'),('俄式小薄餅','ブリヌイ','blini with caviar')],
    [('克里姆林宮','クレムリン','Moscow Kremlin'),('紅場','赤の広場','Red Square'),('聖瓦西里大教堂','聖ワシリイ大聖堂','St Basil Cathedral'),('莫斯科地鐵','モスクワ地下鉄','Moscow Metro')],
    [('勝利日閱兵','戦勝記念日パレード','Victory Day Parade'),('莫斯科城市日','モスクワ市の日','Moscow City Day')]),
2: ('モスクワ州','莫斯科州','中央',
    ('聖三一修道院與銀環小鎮，圍繞首都的歷史帶。','至聖三者聖セルギイ大修道院と銀の環、首都を囲む歴史地帯。','The Trinity Lavra and Silver Ring towns surrounding the capital.'),
    [('圖拉式薑餅','トゥーラ風プリャニク','Tula-style pryanik'),('謝爾蓋耶夫小籠包','セルギエフ・パサードの餃子','Sergiev Posad pelmeni'),('樺木汁','白樺の樹液','birch sap')],
    [('聖三一謝爾蓋大修道院','至聖三者聖セルギイ大修道院','Trinity Sergius Lavra'),('阿布拉姆采沃莊園','アブラムツェヴォ荘園','Abramtsevo Estate'),('柴可夫斯基故居博物館','チャイコフスキー記念館（クリン）','Tchaikovsky House Museum in Klin'),('扎賴斯克克里姆林宮','ザライスクのクレムリン','Zaraysk Kremlin')],
    [('謝肉節慶典','マースレニツァ祭','Maslenitsa festival'),('莫斯科郊外莊園節','郊外荘園の音楽祭','Manor music festivals')]),
3: ('ベルゴロド州','別爾哥羅德州','中央',
    ('俄烏邊境的白色之城，以白堊山丘聞名。','ウクライナ国境の白い街、白亜の丘で知られる。','The white city on the Russian-Ukrainian border, famous for its chalk hills.'),
    [('別爾哥羅德蜂蜜','ベルゴロドの蜂蜜','Belgorod honey'),('鄉村酸奶油燉菜','田舎風スメタナ煮込み','village smetana stew'),('烤餡餅','焼きピロシキ','baked pirozhki')],
    [('白堊山丘','白亜の丘','Belaya Gora chalk hills'),('大教堂廣場','大聖堂広場','Cathedral Square'),('博物館防線','博物館ディオラマ','Museum-Diorama Battle of Kursk'),('森林國家公園','森林国立公園','Forest National Park')],
    [('勝利日慶典','戦勝記念日','Victory Day celebrations'),('蜂蜜節','ハチミツ祭り','Honey Festival')]),
4: ('ブリャンスク州','布良斯克州','中央',
    ('森林覆蓋的邊境州，帕爾季贊游擊隊的故鄉。','森に覆われた国境の州、パルチザンの故郷。','A forested border region, home of the wartime partisans.'),
    [('布良斯克馬鈴薯煎餅','ブリャンスクのポテトパンケーキ','Bryansk potato pancakes'),('野莓果醬','森のベリージャム','wild berry jam'),('克瓦斯','クヴァス','kvass')],
    [('斯文斯基修道院','スヴェンスキー修道院','Svensky Monastery'),('托爾斯托奇村','トルストチ村','Tolstopaltsevo'),('帕爾季贊紀念碑','パルチザン記念碑','Partisan Memorial'),('森林野生動物園','森林動物園','Forest Zoo')],
    [('森林節','森林祭り','Forest Festival'),('斯拉夫文字節','スラヴ文字の日','Slavic Writing Day')]),
5: ('ウラジーミル州','弗拉基米爾州','中央',
    ('金環上的白石教堂，蘇茲達爾的木造小鎮。','黄金の環の白石教会、スーズダリの木造の町。','White-stone cathedrals of the Golden Ring and the wooden town of Suzdal.'),
    [('蘇茲達爾蜂蜜酒','スーズダリの蜂蜜酒','Suzdal mead'),('弗拉基米爾櫻桃','ウラジーミルのチェリー','Vladimir cherries'),('鄉村餡餅','田舎風ピロシキ','country pirozhki')],
    [('聖母升天大教堂','生神女就寝大聖堂','Dormition Cathedral'),('金門','黄金の門','Golden Gate'),('蘇茲達爾克里姆林宮','スーズダリのクレムリン','Suzdal Kremlin'),('木造建築博物館','木造建築博物館','Museum of Wooden Architecture')],
    [('黃瓜節','キュウリ祭り','Cucumber Festival in Suzdal'),('金環音樂節','黄金の環音楽祭','Golden Ring Music Festival')]),
6: ('ヴォロネジ州','沃羅涅日州','中央',
    ('黑土之都，彼得大帝造船的南俄大城。','黒土の都、ピョートル大帝が造船した南ロシアの大都市。','The capital of black earth, where Peter the Great built his first fleet.'),
    [('沃羅涅日香腸','ヴォロネジソーセージ','Voronezh sausage'),('黑土蜂蜜','黒土の蜂蜜','black-earth honey'),('布林餅配魚子醬','ブリヌイとキャビア','blini with caviar')],
    [('彼得大帝紀念碑','ピョートル大帝記念碑','Monument to Peter the Great'),('沃羅涅日水庫','ヴォロネジ貯水池','Voronezh Reservoir'),('阿列克謝耶夫修道院','アレクセーエフスキー修道院','Alekseyevo-Akatov Monastery'),('利斯基教堂群','リスキの教会群','Liski churches')],
    [('城市日慶典','市の日','City Day'),('艦隊節','艦隊の日','Fleet Day')]),
7: ('イヴァノヴォ州','伊萬諾沃州','中央',
    ('俄羅斯紡織之都，革命女工的紅色城市。','ロシアの繊維の都、革命の女工たちの赤い街。','The textile capital of Russia, a red city of revolutionary workers.'),
    [('伊萬諾沃麵包','イヴァノヴォのパン','Ivanovo bread'),('鄉村酸奶油','田舎のスメタナ','village smetana'),('蘋果派','アップルパイ','apple pie')],
    [('紡織博物館','織物博物館','Textile Museum'),('革命廣場','革命広場','Revolution Square'),('舒亞教堂鐘樓','シューヤの鐘楼','Shuya bell tower'),('普廖斯伏爾加河','プリョスのヴォルガ','Plyos on the Volga')],
    [('紡織工人節','織物労働者の日','Textile Workers Day'),('伏爾加河船遊','ヴォルガ川クルーズ','Volga river cruise')]),
8: ('カルーガ州','卡盧加州','中央',
    ('太空先驅齊奧爾科夫斯基之城。','宇宙飛行の先駆者ツィオルコフスキーの街。','The city of space pioneer Konstantin Tsiolkovsky.'),
    [('卡盧加麵團派','カルーガのテースト','Kaluga dough pastry'),('森林蘑菇湯','森のキノコスープ','forest mushroom soup'),('黑麥麵包','ライ麦パン','rye bread')],
    [('齊奧爾科夫斯基宇航博物館','ツィオルコフスキー宇宙博物館','Tsiolkovsky State Museum of Cosmonautics'),('卡盧加石橋','カルーガの石橋','Kaluga stone bridge'),('三一大教堂','至聖三者大聖堂','Trinity Cathedral'),('沃羅特恩斯克遺址','ヴォロティンスク遺跡','Vorotynsk ruins')],
    [('宇航日慶典','宇宙飛行士の日','Cosmonautics Day'),('城市日','市の日','City Day')]),
9: ('コストロマ州','科斯特羅馬州','中央',
    ('羅曼諾夫王朝的搖籃，伏爾加河畔的舊都。','ロマノフ王朝発祥の地、ヴォルガ川の古都。','Cradle of the Romanov dynasty on the Volga.'),
    [('科斯特羅馬奶酪','コストロマチーズ','Kostroma cheese'),('斯米爾諾夫伏特加','スミルノフ・ウォッカ','Smirnov vodka'),('樺樹皮工藝','白樺細工','birch-bark crafts')],
    [('伊帕季耶夫修道院','イパチエフ修道院','Ipatiev Monastery'),('主顯大教堂','公現大聖堂','Epiphany Cathedral'),('木造建築博物館','木造建築博物館','Museum of Wooden Architecture'),('雪姑娘之家','スネグーラチカの家','Residence of Snegurochka')],
    [('奶酪節','チーズ祭り','Cheese Festival'),('斯涅古羅奇卡冬祭','スネグーラチカ冬祭り','Snegurochka Winter Festival')]),
10: ('クルスク州','庫爾斯克州','中央',
    ('庫爾斯克戰役之地，夜鶯之城。','クルスクの戦いの地、ナイチンゲールの街。','Land of the Battle of Kursk, the city of nightingales.'),
    [('庫爾斯克夜鶯甜點','クルスクのナイチンゲール菓子','Kursk nightingale pastry'),('鄉村蘑菇醃菜','田舎のキノコ漬け','pickled forest mushrooms'),('烤乳豬','子豚のロースト','roast suckling pig')],
    [('庫爾斯克戰役博物館','クルスクの戦い博物館','Kursk Battle Museum'),('勝利弧線紀念碑','勝利の弧記念碑','Arc of Victory'),('謝爾吉耶夫-卡贊大教堂','セルギエフ・カザン大聖堂','Sergius-Kazan Cathedral'),('中央黑土自然保護區','中央黒土自然保護区','Central Black Earth Reserve')],
    [('庫爾斯克戰役紀念日','クルスクの戦い記念日','Battle of Kursk Day'),('夜鶯節','ナイチンゲール祭り','Nightingale Festival')]),
11: ('リペツク州','利佩茨克州','中央',
    ('礦泉水療養與鐵鋼之城。','ミネラルウォーターの保養地と鉄鋼の街。','A spa town of mineral waters and a steel city.'),
    [('利佩茨克礦泉水','リペツクのミネラルウォーター','Lipetsk mineral water'),('彼得羅夫蛋糕','ペトロフスキーケーキ','Petrovsky cake'),('鐵鋼廠餐廳牛排','製鉄所のビーフステーキ','steelworks steak')],
    [('礦泉公園','鉱泉公園','Mineral Springs Park'),('耶列茨花邊','エレツのレース','Yelets lace'),('彼得大帝紀念碑','ピョートル大帝記念碑','Peter the Great Monument'),('主升天教堂','昇天教会','Ascension Church')],
    [('城市日','市の日','City Day'),('花邊節','レース祭り','Lace Festival')]),
12: ('オリョール州','奧廖爾州','中央',
    ('屠格涅夫與布寧的文學之城。','ツルゲーネフとブーニンの文学の街。','Literary city of Turgenev and Bunin.'),
    [('奧廖爾麵包圈','オリョールのブーブリク','Oryol baranki'),('蕎麥粥','そば粥','buckwheat kasha'),('蘋果酒','シードル','local cider')],
    [('屠格涅夫莊園','ツルゲーネフ記念館','Turgenev Museum'),('斯帕斯科耶-盧托維諾沃莊園','スパスコエ・ルトヴィノヴォ','Spasskoye-Lutovinovo Estate'),('布寧故居','ブーニン邸','Bunin House'),('奧卡河畔','オカ川のほとり','Oka riverbank')],
    [('屠格涅夫文學節','ツルゲーネフ文学祭','Turgenev Literary Festival'),('城市日','市の日','City Day')]),
13: ('リャザン州','梁贊州','中央',
    ('中世紀俄羅斯的邊防要衝，葉賽寧的故鄉。','中世ロシアの防衛拠点、エセーニンの故郷。','A medieval border fortress, hometown of poet Yesenin.'),
    [('梁贊薑餅','リャザンのプリャニク','Ryazan pryanik'),('卡洛姆納蘋果醬','コロムナのアップルジャム','apple jam'),('蜂蜜格瓦斯','ハチミツクヴァス','honey kvass')],
    [('梁贊克里姆林宮','リャザン・クレムリン','Ryazan Kremlin'),('葉賽寧莊園','エセーニン記念館','Yesenin Museum'),('波薩德木屋街','ポサードの木造家並み','Posad wooden houses'),('梅謝拉國家公園','メシチョラ国立公園','Meshchyora National Park')],
    [('克里姆林音樂節','クレムリン音楽祭','Kremlin Music Festival'),('蘋果節','リンゴ祭り','Apple Festival')]),
14: ('スモレンス克州','斯摩棱斯克州','中央',
    ('俄羅斯之盾，千年要塞古城。','ロシアの盾、千年の要塞都市。','The shield of Russia, a thousand-year-old fortress city.'),
    [('斯摩棱斯克蜂蜜蛋糕','スモレンスクの蜂蜜ケーキ','Smolensk honey cake'),('烤黑麵包','焼きライ麦パン','baked rye bread'),('蘑菇燉湯','キノコのシチュー','mushroom stew')],
    [('斯摩棱斯克克里姆林宮城牆','スモレンスクの城壁','Smolensk Kremlin walls'),('聖母升天大教堂','生神女就寝大聖堂','Dormition Cathedral'),('戰爭英雄紀念碑','大祖国戦争記念碑','War Heroes Memorial'),('巴赫拉切夫花園','バフラチェフ庭園','Bakhlachev Garden')],
    [('城市日','市の日','City Day'),('要塞節','要塞祭り','Fortress Festival')]),
15: ('タンボフ州','坦波夫州','中央',
    ('俄羅斯腹地的音樂之城，坦波夫狼的傳說。','ロシアの内陸の音楽の街、タンボフ狼の伝説。','Music city of the Russian heartland, famous for the Tambov wolf.'),
    [('坦波夫土豆','タンボフのジャガイモ','Tambov potatoes'),('酸奶油燉肉','スメタナ煮込み','smetana stew'),('鄉村果醬','田舎のジャム','homemade jam')],
    [('坦波夫州戲劇院','タンボフ演劇劇場','Tambov Drama Theatre'),('拉赫馬尼諾夫故居','ラフマニノフ記念館','Rachmaninoff Estate in Ivanovka'),('喀山修道院','カザン修道院','Kazan Monastery'),('坦波夫狼雕像','タンボフ狼の像','Tambov Wolf statue')],
    [('拉赫馬尼諾夫音樂節','ラフマニノフ音楽祭','Rachmaninoff Music Festival'),('城市日','市の日','City Day')]),
16: ('トヴェリ州','特維爾州','中央',
    ('伏爾加河源頭之城，莫斯科與聖彼得堡之間。','ヴォルガ川の水源の街、モスクワとペテルブルクの間。','City on the Volga headwaters between Moscow and St Petersburg.'),
    [('特維爾麵包圈','トヴェリのブーブリク','Tver baranki'),('魚湯','フィッシュスープ','fish soup'),('越橘蜜餞','リンゴンベリーの甘露煮','lingonberry compote')],
    [('特維爾帝國旅行宮殿','トヴェリの旅の宮殿','Tver Imperial Travel Palace'),('伏爾加河源頭','ヴォルガ川の源','Volga river source'),('舊沃爾日斯克','スタリツァ修道院','Staritsa Monastery'),('奧斯塔什科夫','オスタシコフ','Ostashkov old town')],
    [('伏爾加節','ヴォルガ祭り','Volga Festival'),('城市日','市の日','City Day')]),
17: ('トゥーラ州','圖拉州','中央',
    ('茶炊與薑餅之城，托爾斯泰的故鄉。','サモワールとプリャニクの街、トルストイの故郷。','City of samovars and pryanik, home of Leo Tolstoy.'),
    [('圖拉薑餅','トゥーラのプリャニク','Tula pryanik'),('圖拉茶炊麵包','サモワール・パン','samovar-shaped bread'),('蜂蜜','はちみつ','local honey')],
    [('圖拉克里姆林宮','トゥーラ・クレムリン','Tula Kremlin'),('雅斯納亞-波利亞納（托爾斯泰莊園）','ヤースナヤ・ポリャーナ','Yasnaya Polyana'),('茶炊博物館','サモワール博物館','Samovar Museum'),('武器博物館','武器博物館','Tula Arms Museum')],
    [('圖拉薑餅節','プリャニク祭り','Pryanik Festival'),('茶炊節','サモワール祭り','Samovar Festival')]),
18: ('ヤロスラヴリ州','雅羅斯拉夫爾州','中央',
    ('伏爾加河畔的世界遺產古城，金環之都。','ヴォルガ川の世界遺産の古都、黄金の環の都。','A UNESCO-listed Volga city, capital of the Golden Ring.'),
    [('雅羅斯拉夫爾麵包','ヤロスラヴリのパン','Yaroslavl bread'),('熊蜜餌餅','クマの形のジンジャーブレッド','bear-shaped gingerbread'),('伏爾加魚子','ヴォルガのキャビア','Volga caviar')],
    [('主顯教堂與斯帕索修道院','公現大聖堂とスパソ修道院','Epiphany Cathedral and Spaso-Preobrazhensky Monastery'),('先知伊利亞教堂','預言者イリヤ教会','Church of Elijah the Prophet'),('托爾加修道院','トルガ修道院','Tolga Convent'),('伏爾加河堤','ヴォルガ川の堤防','Volga embankment')],
    [('城市日','市の日','City Day'),('金環音樂節','黄金の環音楽祭','Golden Ring Music Festival')]),
19: ('サンクトペテルブルク市','聖彼得堡市','西北',
    ('北方威尼斯，冬宮與白夜的帝國首都。','北のヴェネツィア、エルミタージュと白夜の帝都。','The Venice of the North — imperial capital of the Hermitage and White Nights.'),
    [('俄式煎餅配魚子醬','ブリヌイとキャビア','blini with caviar'),('皮羅什基','ピロシキ','pirozhki'),('蜂蜜蛋糕','蜂蜜ケーキ','medovik honey cake')],
    [('冬宮與國立艾爾米塔什博物館','エルミタージュ美術館','Hermitage Museum'),('彼得保羅要塞','ペトロパヴロフスク要塞','Peter and Paul Fortress'),('滴血大教堂','血の上の救世主教会','Church of the Saviour on Spilled Blood'),('涅瓦河夜遊','ネヴァ川クルーズ','Neva river cruise')],
    [('白夜節','白夜祭り','White Nights Festival'),('紅帆節','緋色の帆祭り','Scarlet Sails Festival')]),
20: ('レニングラード州','列寧格勒州','西北',
    ('環繞彼得堡的湖泊森林，皇村與要塞。','ペテルブルクを囲む湖と森、皇村と要塞。','Lakes and forests around Petersburg — Tsarskoye Selo and island forts.'),
    [('卡累利阿派','カレリア風パイ','Karelian pie'),('熏魚','スモークフィッシュ','smoked fish'),('越橘茶','リンゴンベリーティー','lingonberry tea')],
    [('葉卡捷琳娜宮（皇村）','エカテリーナ宮殿','Catherine Palace in Tsarskoye Selo'),('彼得霍夫宮','ペテルゴフ宮殿','Peterhof Palace'),('科特林島要塞','クロンシュタット要塞','Kronstadt fortress'),('拉多加湖','ラドガ湖','Lake Ladoga')],
    [('白夜節','白夜祭り','White Nights'),('彼得霍夫噴泉節','ペテルゴフ噴水祭り','Peterhof Fountain Festival')]),
21: ('アルハンゲリスク州','阿爾漢格爾斯克州','西北',
    ('白海之港，索洛韋茨基群島與北極門戶。','白海の港、ソロヴェツキー諸島と北極の玄関。','White Sea port, gateway to the Arctic and the Solovetsky Islands.'),
    [('白海鱈魚','白海のタラ','White Sea cod'),('北方漿果果醬','北のベリージャム','northern berry jam'),('鹿肉排','トナカイステーキ','reindeer steak')],
    [('索洛韋茨基修道院','ソロヴェツキー修道院','Solovetsky Monastery'),('阿爾漢格爾斯克海濱','アルハンゲリスクの堤防','Arkhangelsk embankment'),('木造建築博物館小卡列利','マールイエ・カレールイ','Malye Karely open-air museum'),('白海','白海','White Sea')],
    [('白海節','白海祭り','White Sea Festival'),('北方之夜慶典','北の夜祭り','Northern Nights Festival')]),
22: ('ヴォログダ州','沃洛格達州','西北',
    ('北方威尼斯？不，這裡是奶油與蕾絲之鄉。','バターとレースの郷、北方の古都。','Land of butter and lace, ancient northern capital.'),
    [('沃洛格達奶油','ヴォログダバター','Vologda butter'),('沃洛格達麵包圈','ヴォログダのブーブリク','Vologda baranki'),('乳酪凝塊','セルニキ','syrniki cottage cheese pancakes')],
    [('沃洛格達克里姆林宮','ヴォログダ・クレムリン','Vologda Kremlin'),('基里爾-別洛澤爾斯基修道院','キリロ・ベロゼルスキー修道院','Kirillo-Belozersky Monastery'),('費拉蓬托夫修道院','フェラポントフ修道院','Ferapontov Monastery'),('蕾絲博物館','レース博物館','Lace Museum')],
    [('奶油節','バター祭り','Butter Festival'),('城市日','市の日','City Day')]),
23: ('カリーニングラ徳州','加里寧格勒州','西北',
    ('俄羅斯的歐洲飛地，琥珀之都柯尼斯堡。','ロシアの飛び地、琥珀の都ケーニヒスベルク。','Russia in Europe — the amber city of Königsberg.'),
    [('琥珀蜜餞','琥珀の砂糖菓子','amber-shaped candy'),('柯尼斯堡肉丸','ケーニヒスベルガー・クロプセ','Königsberger meatballs'),('燻鯡魚','スモークニシン','smoked herring')],
    [('柯尼斯堡大教堂','ケーニヒスベルク大聖堂','Königsberg Cathedral'),('琥珀博物館','琥珀博物館','Amber Museum'),('庫爾什沙嘴','クルシュー砂州','Curonian Spit'),('海洋博物館','海洋博物館','Museum of the World Ocean')],
    [('城市日','市の日','City Day'),('琥珀節','琥珀祭り','Amber Festival')]),
24: ('カレリア共和国','卡累利阿共和國','西北',
    ('千湖之國，基日島的木造奇蹟。','千の湖の国、キジ島の木造の奇跡。','Land of a thousand lakes — the wooden wonder of Kizhi Island.'),
    [('卡累利阿魚派','カレリアの魚パイ','Karelian fish pie'),('越橘果醬','リンゴンベリージャム','lingonberry jam'),('卡累利阿燉魚湯','カレリア風フィッシュシチュー','Karelian fish stew')],
    [('基日島木造教堂','キジ島の木造教会','Kizhi Pogost'),('魯斯卡拉大理石峽谷','ルスケアラ大理石峡谷','Ruskeala Marble Canyon'),('奧涅加湖','オネガ湖','Lake Onega'),('彼得羅扎沃茨克濱海','ペトロザヴォーツクの堤防','Petrozavodsk embankment')],
    [('卡累利阿民歌節','カレリア民謡祭り','Karelian folk festival'),('基日島慶典','キジ島の祭典','Kizhi celebrations')]),
25: ('コミ共和国','科米共和國','西北',
    ('原始針葉林的世遺，北極圈內的凍土。','原生タイガの世界遺産、北極圏の大地。','Virgin taiga of world-heritage status on the Arctic Circle.'),
    [('科米燉肉','コミ風煮込み','Komi meat stew'),('馴鹿肉乾','トナカイの干し肉','dried reindeer meat'),('松子','松の実','pine nuts')],
    [('原始科米森林','コミの原生林','Virgin Komi Forests'),('曼普普涅爾岩柱','マンププニョル岩柱','Manpupuner rock formations'),('瑟克特夫卡爾市中心','スィクティフカル中心部','Syktyvkar city centre'),('烏赫塔油田紀念碑','ウフタ油田記念碑','Ukhta oil monument')],
    [('馴鹿牧民節','トナカイ遊牧民の祭り','Reindeer herders festival'),('城市日','市の日','City Day')]),
26: ('ムルマンス克州','摩爾曼斯克州','西北',
    ('北極圈內的極光之城，不凍港。','北極圏のオーロラの街、不凍港。','The aurora city inside the Arctic Circle, an ice-free port.'),
    [('北極鱈魚湯','北極のタラスープ','Arctic cod soup'),('馴鹿肉丸','トナカイミートボール','reindeer meatballs'),('北方海膽','ウニ','sea urchin')],
    [('極光觀測','オーロラ観測','Aurora watching'),('阿廖沙紀念碑','アリョーシャ記念碑','Alyosha Monument'),('核動力破冰船列寧號','原子力砕氷船レーニン','Nuclear icebreaker Lenin'),('捷里別爾卡海岸','テリベルカ海岸','Teriberka coast')],
    [('北極節','北極祭り','Arctic Festival'),('極夜日出慶典','極夜明けの祭り','Polar night sunrise')]),
27: ('ネネツ自治管区','涅涅茨自治區','西北',
    ('凍原上的馴鹿游牧，俄羅斯最北的管區。','ツンドラのトナカイ遊牧、ロシア最北の管区。','Reindeer nomads of the tundra, Russia northernmost region.'),
    [('馴鹿肉湯','トナカイのスープ','reindeer soup'),('凍原莓果','ツンドラのベリー','tundra berries'),('魚乾','干し魚','dried fish')],
    [('納里揚馬爾市中心','ナリヤン・マル中心部','Naryan-Mar town'),('凍原景觀','ツンドラの風景','Arctic tundra'),('白海海豹棲地','アザラシの生息地','seal colonies'),('佩喬拉河','ペチョラ川','Pechora river')],
    [('馴鹿牧民日','トナカイ遊牧民の日','Reindeer Herders Day'),('極夜節','極夜祭り','Polar Night Festival')]),
28: ('ノヴゴロ德州','諾夫哥羅德州','西北',
    ('俄羅斯之母，中世紀的議會共和國。','ロシアの母、中世の共和国都市。','Mother of Russian cities, medieval republic of veche.'),
    [('諾夫哥羅德蜂蜜麵包','ノヴゴロドの蜂蜜パン','Novgorod honey bread'),('烤魚','焼き魚','grilled fish'),('克瓦斯','クヴァス','kvass')],
    [('聖索菲亞大教堂','聖ソフィア大聖堂','St Sophia Cathedral'),('諾夫哥羅德克里姆林宮','ノヴゴロド・デティネツ','Novgorod Kremlin'),('尤里耶夫修道院','ユーリエフ修道院','Yuriev Monastery'),('伊利亞湖','イルメニ湖','Lake Ilmen')],
    [('諾夫哥羅德城市日','市の日','Novgorod City Day'),('中世紀慶典','中世フェスティバル','Medieval Festival')]),
29: ('プスコフ州','普斯科夫州','西北',
    ('千年要塞，普斯科夫教堂學派的世遺。','千年の要塞、プスコフ建築学派の世界遺産。','Thousand-year fortress, home of the UNESCO-listed Pskov school of architecture.'),
    [('普斯科夫烤鱒魚','プスコフのマス料理','Pskov trout'),('蜂蜜酒','蜂蜜酒','local mead'),('黑麥麵包圈','ライ麦ブーブリク','rye baranki')],
    [('普斯科夫克里姆林宮','プスコフ・クロム','Pskov Krom'),('三一大教堂','至聖三者大聖堂','Trinity Cathedral'),('米羅日修道院','ミロジ修道院','Mirozhsky Monastery'),('普希金山莊園','プーシキン山荘','Pushkin Hills (Mikhailovskoye)')],
    [('普斯科夫城市日','市の日','Pskov City Day'),('普希金詩歌節','プーシキン詩祭り','Pushkin Poetry Festival')]),
30: ('アディゲ共和国','阿迪格共和國','南方',
    ('高加索西部的山麓共和國，民族風情濃厚。','西カフカスの山麓の共和国、民族色豊か。','Mountainous republic of the Western Caucasus with rich folk traditions.'),
    [('阿迪格奶酪','アディゲチーズ','Adyghe cheese'),('烤肉串','シャシリク','shashlik'),('玉米粥配奶酪','アディゲ風ポレンタ','Adyghe polenta with cheese')],
    [('拉戈-納基高原','ラゴ・ナキ高原','Lago-Naki plateau'),('哈喬赫峽谷','ハジョフ峡谷','Khadzhokh canyon'),('邁科普大清真寺','マイコープ大モスク','Maykop Grand Mosque'),('民族博物館','民族博物館','National Museum of Adygea')],
    [('阿迪格民族節','アディゲ民族祭り','Adyghe National Day'),('奶酪節','チーズ祭り','Cheese Festival')]),
31: ('カルムイク共和国','卡爾梅克共和國','南方',
    ('歐洲唯一的佛教共和國，草原上的蒙古文化。','ヨーロッパ唯一の仏教共和国、草原のモンゴル文化。','Europes only Buddhist republic, Mongolian culture on the steppe.'),
    [('卡爾梅克茶','カルムイク茶','Kalmyk tea'),('羊肉餃子','羊肉の餃子','mutton dumplings'),('馬奶酒','馬乳酒','fermented mare milk')],
    [('金色佛寺','黄金の仏教寺院','Golden Abode of Buddha'),('埃利斯塔棋城','エリスタのチェス都市','Chess City in Elista'),('大草原','カルムイク草原','Kalmyk steppe'),('駱駝牧場','ラクダ牧場','camel farm')],
    [('祖爾節','ズル祭り','Zul festival'),('草原節','草原祭り','Steppe Festival')]),
32: ('クラスノダール地方','克拉斯諾達爾邊疆區','南方',
    ('俄羅斯度假勝地，索契與黑海海岸。','ロシアのリゾート地、ソチと黒海沿岸。','The Russian Riviera — Sochi and the Black Sea coast.'),
    [('紅甜菜沙拉','オリヴィエ風サラダ','vinegret salad'),('黑海魚湯','黒海の魚介','Black Sea seafood'),('亞德雷麵包','アディゲパン','local bread')],
    [('索契奧林匹克公園','ソチ・オリンピック公園','Sochi Olympic Park'),('羅莎庫托爾滑雪場','ローザ・フトル','Rosa Khutor ski resort'),('阿古爾峽谷','アグール峡谷','Agur waterfall canyon'),('紅波利亞納','クラスナヤ・ポリャーナ','Krasnaya Polyana')],
    [('索契國際電影節','ソチ国際映画祭','Sochi International Film Festival'),('黑海帆船節','黒海ヨット祭り','Black Sea Regatta')]),
33: ('アストラハン州','阿斯特拉罕州','南方',
    ('伏爾加河三角洲，魚子醬與蓮花之鄉。','ヴォルガデルタ、キャビアと蓮の郷。','Volga delta — land of caviar and lotus flowers.'),
    [('黑魚子醬','黒キャビア','black caviar'),('阿斯特拉罕西瓜','アストラハンのスイカ','Astrakhan watermelon'),('伏爾加魚湯','ヴォルガのウハー','Volga ukha fish soup')],
    [('阿斯特拉罕克里姆林宮','アストラハン・クレムリン','Astrakhan Kremlin'),('伏爾加河三角洲蓮花田','ヴォルガデルタの蓮','Volga delta lotus fields'),('魚子醬博物館','キャビア博物館','Caviar Museum'),('星際空間博物館','宇宙博物館','Space Museum')],
    [('蓮花節','蓮祭り','Lotus Festival'),('西瓜節','スイカ祭り','Watermelon Festival')]),
34: ('ヴォルゴグラード州','伏爾加格勒州','南方',
    ('史達林格勒戰役之城，馬馬耶夫崗上的祖國母親。','スターリングラードの戦いの街、ママエフの丘の母なる祖国像。','City of the Battle of Stalingrad and the Motherland Calls statue.'),
    [('伏爾加格勒芥末','ヴォルゴグラードのマスタード','Volgograd mustard'),('羅宋湯','ボルシチ','borscht'),('烤魚','焼き魚','grilled Volga fish')],
    [('馬馬耶夫崗與祖國母親雕像','ママエフの丘と母なる祖国像','Mamayev Kurgan and Motherland Calls'),('伏爾加格勒全景博物館','スターリングラード戦博物館','Stalingrad Battle Panorama Museum'),('伏爾加河碼頭','ヴォルガ川の埠頭','Volga embankment'),('察里津舊城區','ツァリーツィン旧市街','Old Tsaritsyn district')],
    [('勝利日紀念','戦勝記念日','Victory Day'),('城市日','市の日','City Day')]),
35: ('ロストフ州','羅斯托夫州','南方',
    ('頓河之都，哥薩克文化的中心。','ドン川の都、コサック文化の中心。','Capital of the Don region, heart of Cossack culture.'),
    [('羅斯托夫燉魚湯','ロストフの魚スープ','Rostov fish soup'),('哥薩克烤肉','コサック風シャシリク','Cossack shashlik'),('向日葵種子麵包','ひまわりの種パン','sunflower seed bread')],
    [('羅斯托夫濱河街','ロストフの堤防','Rostov embankment'),('大劇院廣場','劇場広場','Theatre Square'),('舊切爾卡斯克','スタロチェルカスカヤ','Starocherkasskaya village'),('頓河','ドン川','Don river')],
    [('哥薩克節','コサック祭り','Cossack Festival'),('城市日','市の日','City Day')]),
36: ('ダゲスタン共和国','達吉斯坦共和國','北高加索',
    ('山巒之國，傑爾賓特的千年城牆。','山々の国、デルベントの千年の城壁。','Land of mountains, home to the thousand-year walls of Derbent.'),
    [('達吉斯坦烤肉','ダゲスタン風シャシリク','Dagestani shashlik'),('楚杜爾薄餅','チュドゥル','chudu flatbread'),('山區蜂蜜','山岳はちみつ','mountain honey')],
    [('傑爾賓特要塞','デルベント要塞','Derbent Citadel'),('蘇拉克峽谷','スラク峡谷','Sulak Canyon'),('吉姆里山隧道','ギムリ山岳','Gimry mountains'),('馬哈奇卡拉海岸','マハチカラ海岸','Makhachkala seaside')],
    [('民族舞蹈節','民族舞踊祭り','Folk Dance Festival'),('蜂蜜節','ハチミツ祭り','Honey Festival')]),
37: ('イングーシ共和国','印古什共和國','北高加索',
    ('高塔之國，中世紀石塔與峽谷。','石の塔の国、中世の石塔と峡谷。','Land of ancient stone towers and gorges.'),
    [('印古什烤肉','イングーシ風シャシリク','Ingush shashlik'),('玉米麵包','コーンブレッド','cornbread'),('山區奶酪','山のチーズ','mountain cheese')],
    [('杰伊拉赫-阿西峽谷','ジェイラフ・アッシ峡谷','Dzheyrakh-Assa gorge'),('埃吉卡爾石塔','エギカル石塔','Egiqal towers'),('沃夫努什基城堡','ヴォヴヌシュキ','Vovnushki towers'),('阿爾姆希城堡','アルムヒ','Almhi castle')],
    [('石塔節','石塔祭り','Tower Festival'),('民族日','民族の日','National Day')]),
38: ('カバルダ・バルカル共和国','卡巴爾達-巴爾卡爾共和國','北高加索',
    ('厄爾布魯士峰所在的雪山共和國。','エルブルス山を擁する雪の山岳共和国。','Mountain republic crowned by Mount Elbrus.'),
    [('巴爾卡爾烤肉','バルカル風シャシリク','Balkar shashlik'),('希奇恩奶酪','ヒチン・チーズ','khychin flatbread with cheese'),('山區蜂蜜','山岳はちみつ','mountain honey')],
    [('厄爾布魯士峰','エルブルス山','Mount Elbrus'),('切格姆瀑布','チェゲム滝','Chegem waterfalls'),('巴克桑峽谷','バクサン峡谷','Baksan gorge'),('納爾奇克公園','ナリチク公園','Nalchik parks')],
    [('登山節','登山祭り','Mountaineering Festival'),('民族日','民族の日','National Day')]),
39: ('カラチャイ・チェルケス共和国','卡拉恰伊-切爾克斯共和國','北高加索',
    ('高加索西部的山岳牧場共和國。','西カフカスの山岳牧場の共和国。','Mountain republic of the Western Caucasus high pastures.'),
    [('卡拉恰伊羊肉','カラチャイ風羊肉料理','Karachay lamb dishes'),('奶酪餡餅','チーズパイ','cheese pie'),('山泉蜂蜜','山の泉の蜂蜜','mountain honey')],
    [('多姆拜滑雪度假村','ドムバイ','Dombay ski resort'),('捷別爾達自然保護區','テベルダ自然保護区','Teberda Nature Reserve'),('索菲亞冰川','ソフィア氷河','Sofia glacier'),('阿爾希茲修道院','アルヒズ','Nizhny Arkhyz ruins')],
    [('牧羊人節','羊飼いの祭り','Shepherds Festival'),('滑雪節','スキー祭り','Ski Festival')]),
40: ('北オセチア共和国','北奧塞梯共和國','北高加索',
    ('高加索山麓的騎士之國，弗拉季高加索。','カフカスの麓の騎士の国、ウラジカフカス。','Land of knights at the Caucasus foothills, capital Vladikavkaz.'),
    [('奧塞梯餡餅','オセチア・パイ','Ossetian pie'),('羊肉湯','羊肉のスープ','mutton soup'),('山區奶酪','山のチーズ','mountain cheese')],
    [('弗拉季高加索市中心','ウラジカフカス中心部','Vladikavkaz old centre'),('達爾加夫斯死亡之城','ダルガフスの死者の街','Dargavs City of the Dead'),('茨米峽谷','ツミ峡谷','Tseyskoye gorge'),('高加索山脈展望','カフカス山脈展望','Caucasus mountain views')],
    [('奧塞梯民族節','オセチア民族祭り','Ossetian National Day'),('餡餅節','パイ祭り','Ossetian Pie Festival')]),
41: ('チェチェン共和国','車臣共和國','北高加索',
    ('重建中的格羅茲尼，高加索的現代清真寺。','再建されたグロズヌイ、カフカスのモダンなモスク。','Rebuilt Grozny and the modern mosques of the Caucasus.'),
    [('車臣烤肉','チェチェン風シャシリク','Chechen shashlik'),('奶酪餃子','チーズ餃子','cheese dumplings'),('車臣茶','チェチェンティー','Chechen tea')],
    [('艾哈邁德清真寺','アフマド・カディロフ・モスク','Akhmad Kadyrov Mosque'),('格羅茲尼市中心','グロズヌイ中心部','Grozny city centre'),('阿爾貢峽谷','アルグン峡谷','Argun gorge'),('凱澤諾伊-阿姆湖','ケゼノイ・アム湖','Lake Kezenoy-am')],
    [('城市日','市の日','City Day'),('民族舞蹈節','民族舞踊祭り','Folk Dance Festival')]),
42: ('スタヴロ波利地方','斯塔夫羅波爾邊疆區','北高加索',
    ('高加索礦泉城，皮亞季戈爾斯克與溫泉。','カフカースの鉱泉都市、ピャチゴルスクと温泉。','Caucasus mineral springs — Pyatigorsk and its spa towns.'),
    [('礦泉水','ミネラルウォーター','mineral water'),('高加索烤肉','シャシリク','shashlik'),('蜂蜜蛋糕','蜂蜜ケーキ','honey cake')],
    [('皮亞季戈爾斯克','ピャチゴルスク','Pyatigorsk'),('馬舒克山纜車','マシュク山ロープウェイ','Mount Mashuk cable car'),('葉先圖基浴場','エッセントゥキ','Essentuki spa'),('克拉斯諾沃茨克高原','スタヴロポリ高地','Stavropol uplands')],
    [('礦泉節','鉱泉祭り','Mineral Waters Festival'),('城市日','市の日','City Day')]),
}
